version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - core-tenants-networks
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - core-tenants-networks
    restart: unless-stopped

networks:
  core-tenants-networks:
    driver: bridge

volumes:
  postgres:
  pgadmin: